'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Information
    Public Property Id As Integer
    Public Property TenKhachHang As String
    Public Property idLoaiBaoHiem As Nullable(Of Integer)
    Public Property CreateDay As Nullable(Of Date)
    Public Property Address As String

    Public Overridable Property LoaiBaoHiem As LoaiBaoHiem

End Class
