'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LoaiBaoHiem
    Public Property id As Integer
    Public Property LoaiBaoHiem1 As String

    Public Overridable Property Information As ICollection(Of Information) = New HashSet(Of Information)

End Class
